# This is a basic workflow to help you get started with Actions

name: build-check

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest,ubuntu-latest]
        include:
        - os: macos-latest
          CC: clang
          CXX: clang++

        - os: windows-latest
          CXX: cl
          CC: cl

        - os: ubuntu-latest
          CC: clang
          CXX: clang++
        
        - os: ubuntu-latest
          CC: gcc
          CXX: g++

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Get latest CMake
      # Using 'latest' branch, the latest CMake is installed.
      uses: lukka/get-cmake@latest 
      
    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master
      
    - name: Setup VS Environment
      if: startsWith(matrix.os, 'windows')
      uses: seanmiddleditch/gha-setup-vsdevenv@master
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
      
    - name: configure
      env:
        CXX: ${{matrix.CXX}}
        CC: ${{matrix.CC}}
      run: |
        mkdir build
        cd build
        cmake -GNinja -DCMAKE_BUILD_TYPE=RELEASE ..
    - name: build
      run:  cmake --build build --parallel
