# This is a basic workflow to help you get started with Actions

name: build-check

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: "Ubuntu gcc7", os: ubuntu-latest, cc: "gcc-7", cxx: "g++-7" }
          - { name: "Ubuntu gcc10", os: ubuntu-latest, cc: "gcc-10", cxx: "g++-10" }
          - { name: "Ubuntu clang7", os: ubuntu-latest, cc: "clang-7", cxx: "clang-7" }
          - { name: "Ubuntu clang10", os: ubuntu-latest, cc: "clang-10", cxx: "clang-10" }
    steps:
      - name: Install deps    
        run: |
            sudo add-apt-repository ppa:ubuntu-toolchain-r/test
            sudo apt-get update
            sudo apt-get install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev mesa-common-dev clang-10 g++-10 clang-7 g++-7
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master
        with:
          # ninja version to download. Default: 1.10.0
          version: 1.10.0

      - name: Build with CMake
        uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{ runner.workspace }}/build
          cc: ${{ matrix.config.cc }}
          cxx: ${{ matrix.config.cxx }}
          configure-options: -G Ninja
          build-type: Release
